/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const AIRLINES = [
  { name: 'SkyGlide Airways', logo: '✈️', regions: ['Global'], alliance: 'None' },
  { name: 'Oceanic Airlines', logo: '🌊', regions: ['Global'], alliance: 'None' },
  { name: 'Global Connect', logo: '🌐', regions: ['Global'], alliance: 'Star Alliance' },
  { name: 'Vista Jet', logo: '✨', regions: ['Global'], alliance: 'None' },
  { name: 'Air India', logo: '🇮🇳', regions: ['India', 'International'], alliance: 'Star Alliance' },
  { name: 'IndiGo', logo: '✈️', regions: ['India'], alliance: 'None' },
  { name: 'Vistara', logo: '✨', regions: ['India', 'International'], alliance: 'None' },
  { name: 'SpiceJet', logo: '✈️', regions: ['India'], alliance: 'None' },
  { name: 'Akasa Air', logo: '✈️', regions: ['India'], alliance: 'None' },
  { name: 'Air India Express', logo: '✈️', regions: ['India'], alliance: 'None' },
  { name: 'Emirates', logo: '🇦🇪', regions: ['International'], alliance: 'None' },
  { name: 'Singapore Airlines', logo: '🇸🇬', regions: ['International'], alliance: 'Star Alliance' },
  { name: 'Delta Air Lines', logo: '🇺🇸', regions: ['International'], alliance: 'SkyTeam' },
  { name: 'Lufthansa', logo: '🇩🇪', regions: ['International'], alliance: 'Star Alliance' },
  { name: 'Qatar Airways', logo: '🇶🇦', regions: ['International'], alliance: 'Oneworld' }
];

export const AIRPORTS = [
  // Global Major Hubs
  { code: 'JFK', city: 'New York', country: 'USA', name: 'John F. Kennedy International' },
  { code: 'LHR', city: 'London', country: 'UK', name: 'Heathrow Airport' },
  { code: 'HND', city: 'Tokyo', country: 'Japan', name: 'Haneda Airport' },
  { code: 'DXB', city: 'Dubai', country: 'UAE', name: 'Dubai International' },
  { code: 'SIN', city: 'Singapore', country: 'Singapore', name: 'Changi Airport' },
  { code: 'CDG', city: 'Paris', country: 'France', name: 'Charles de Gaulle' },
  { code: 'SFO', city: 'San Francisco', country: 'USA', name: 'San Francisco International' },
  { code: 'SYD', city: 'Sydney', country: 'Australia', name: 'Sydney Airport' },
  { code: 'HKG', city: 'Hong Kong', country: 'China', name: 'Hong Kong International' },
  { code: 'FRA', city: 'Frankfurt', country: 'Germany', name: 'Frankfurt Airport' },
  { code: 'YYZ', city: 'Toronto', country: 'Canada', name: 'Pearson International' },
  { code: 'AMS', city: 'Amsterdam', country: 'Netherlands', name: 'Schiphol Airport' },
  { code: 'IST', city: 'Istanbul', country: 'Turkey', name: 'Istanbul Airport' },
  { code: 'SEA', city: 'Seattle', country: 'USA', name: 'Tacoma International' },
  
  // Indian Hubs & Requested Cities
  { code: 'BOM', city: 'Mumbai', country: 'India', name: 'Chhatrapati Shivaji Maharaj International' },
  { code: 'DEL', city: 'Delhi', country: 'India', name: 'Indira Gandhi International' },
  { code: 'BLR', city: 'Bengaluru', country: 'India', name: 'Kempegowda International' },
  { code: 'MAA', city: 'Chennai', country: 'India', name: 'Chennai International' },
  { code: 'HYD', city: 'Hyderabad', country: 'India', name: 'Rajiv Gandhi International' },
  { code: 'CCU', city: 'Kolkata', country: 'India', name: 'Netaji Subhas Chandra Bose International' },
  { code: 'PAT', city: 'Patna', country: 'India', name: 'Jay Prakash Narayan International' },
  { code: 'VNS', city: 'Varanasi', country: 'India', name: 'Lal Bahadur Shastri International' },
  { code: 'LKO', city: 'Lucknow', country: 'India', name: 'Chaudhary Charan Singh International' },
  { code: 'DED', city: 'Dehradun', country: 'India', name: 'Jolly Grant Airport' },
  { code: 'PNQ', city: 'Pune', country: 'India', name: 'Pune Airport' },
  { code: 'AMD', city: 'Ahmedabad', country: 'India', name: 'Sardar Vallabhbhai Patel International' },
  { code: 'COK', city: 'Kochi', country: 'India', name: 'Cochin International' },
  { code: 'GOI', city: 'Goa', country: 'India', name: 'Dabolim Airport' },
  { code: 'JAI', city: 'Jaipur', country: 'India', name: 'Jaipur International' },
  { code: 'IXC', city: 'Chandigarh', country: 'India', name: 'Shaheed Bhagat Singh International' },
  { code: 'IXJ', city: 'Jammu', country: 'India', name: 'Jammu Airport' },
  { code: 'SXR', city: 'Srinagar', country: 'India', name: 'Sheikh ul-Alam International' },
  { code: 'TRV', city: 'Thiruvananthapuram', country: 'India', name: 'Trivandrum International' },
  { code: 'BBI', city: 'Bhubaneswar', country: 'India', name: 'Biju Patnaik International' },
  { code: 'BDQ', city: 'Vadodara', country: 'India', name: 'Vadodara Airport' },
  { code: 'RPR', city: 'Raipur', country: 'India', name: 'Swami Vivekananda Airport' },
  { code: 'IXR', city: 'Ranchi', country: 'India', name: 'Birsa Munda Airport' },
  { code: 'IDR', city: 'Indore', country: 'India', name: 'Devi Ahilya Bai Holkar International' },
  { code: 'BHO', city: 'Bhopal', country: 'India', name: 'Raja Bhoj Airport' },
  { code: 'NAG', city: 'Nagpur', country: 'India', name: 'Dr. Babasaheb Ambedkar International' },
  { code: 'IXB', city: 'Bagdogra', country: 'India', name: 'Bagdogra International' },
  { code: 'IXW', city: 'Jamshedpur', country: 'India', name: 'Sonari Airport' },
  { code: 'IXZ', city: 'Port Blair', country: 'India', name: 'Veer Savarkar International' },
  { code: 'GAU', city: 'Guwahati', country: 'India', name: 'Lokpriya Gopinath Bordoloi International' },
  { code: 'IMF', city: 'Imphal', country: 'India', name: 'Bir Tikendrajit International' },
  { code: 'IXA', city: 'Agartala', country: 'India', name: 'Maharaja Bir Bikram Airport' },
  { code: 'AJL', city: 'Aizawl', country: 'India', name: 'Lengpui Airport' },
  { code: 'DMU', city: 'Dimapur', country: 'India', name: 'Dimapur Airport' },
  { code: 'SHL', city: 'Shillong', country: 'India', name: 'Shillong Airport' },
  { code: 'UDR', city: 'Udaipur', country: 'India', name: 'Maharana Pratap Airport' },
  { code: 'JDH', city: 'Jodhpur', country: 'India', name: 'Jodhpur Airport' },
  { code: 'IXE', city: 'Mangaluru', country: 'India', name: 'Mangaluru International' },
  { code: 'CJB', city: 'Coimbatore', country: 'India', name: 'Coimbatore International' },
  { code: 'IXM', city: 'Madurai', country: 'India', name: 'Madurai Airport' },
  { code: 'VTZ', city: 'Visakhapatnam', country: 'India', name: 'Visakhapatnam International' },
  { code: 'VGA', city: 'Vijayawada', country: 'India', name: 'Vijayawada Airport' },
  { code: 'TIR', city: 'Tirupati', country: 'India', name: 'Tirupati Airport' },

  // Global Secondary & Emerging Cities
  { code: 'BER', city: 'Berlin', country: 'Germany', name: 'Brandenburg Airport' },
  { code: 'MAD', city: 'Madrid', country: 'Spain', name: 'Adolfo Suárez Barajas' },
  { code: 'FCO', city: 'Rome', country: 'Italy', name: 'Leonardo da Vinci–Fiumicino' },
  { code: 'MEX', city: 'Mexico City', country: 'Mexico', name: 'Benito Juárez International' },
  { code: 'GRU', city: 'São Paulo', country: 'Brazil', name: 'Guarulhos International' },
  { code: 'EZE', city: 'Buenos Aires', country: 'Argentina', name: 'Ministro Pistarini' },
  { code: 'CPT', city: 'Cape Town', country: 'South Africa', name: 'Cape Town International' },
  { code: 'NBO', city: 'Nairobi', country: 'Kenya', name: 'Jomo Kenyatta International' },
  { code: 'MEL', city: 'Melbourne', country: 'Australia', name: 'Melbourne Airport' },
  { code: 'AKL', city: 'Auckland', country: 'New Zealand', name: 'Auckland Airport' },
  { code: 'MNL', city: 'Manila', country: 'Philippines', name: 'Ninoy Aquino International' },
  { code: 'BKK', city: 'Bangkok', country: 'Thailand', name: 'Suvarnabhumi Airport' },
  { code: 'ICN', city: 'Seoul', country: 'South Korea', name: 'Incheon International' },
  { code: 'ZRH', city: 'Zurich', country: 'Switzerland', name: 'Zurich Airport' },
  { code: 'VIE', city: 'Vienna', country: 'Austria', name: 'Vienna International' },
  { code: 'OSL', city: 'Oslo', country: 'Norway', name: 'Oslo Airport' },
  { code: 'ARN', city: 'Stockholm', country: 'Sweden', name: 'Arlanda Airport' },
  { code: 'HEL', city: 'Helsinki', country: 'Finland', name: 'Helsinki Airport' },
  { code: 'CPH', city: 'Copenhagen', country: 'Denmark', name: 'Copenhagen Airport' },
  { code: 'DUB', city: 'Dublin', country: 'Ireland', name: 'Dublin Airport' },
  { code: 'LIS', city: 'Lisbon', country: 'Portugal', name: 'Humberto Delgado Airport' },
  { code: 'BCN', city: 'Barcelona', country: 'Spain', name: 'El Prat Airport' },
  { code: 'ATH', city: 'Athens', country: 'Greece', name: 'Eleftherios Venizelos' },
  { code: 'WAW', city: 'Warsaw', country: 'Poland', name: 'Chopin Airport' },
  { code: 'CAI', city: 'Cairo', country: 'Egypt', name: 'Cairo International' },
  { code: 'CMN', city: 'Casablanca', country: 'Morocco', name: 'Mohammed V International' },
  { code: 'JNB', city: 'Johannesburg', country: 'South Africa', name: 'O.R. Tambo International' },
  { code: 'SCL', city: 'Santiago', country: 'Chile', name: 'Arturo Merino Benítez' },
  { code: 'LIM', city: 'Lima', country: 'Peru', name: 'Jorge Chávez International' },
  { code: 'BOG', city: 'Bogotá', country: 'Colombia', name: 'El Dorado International' },
  { code: 'DOH', city: 'Doha', country: 'Qatar', name: 'Hamad International' },
  { code: 'YVR', city: 'Vancouver', country: 'Canada', name: 'Vancouver International' }
];

export const FLIGHT_CLASSES = ['Economy', 'Business', 'First'];
